### ISSUE TITLE
Intro vignette

### ISSUE THREAD

**Issue by cwschultz88** [UptakeOpenSource/updraft#10]
Write a couple of R vignettes that demonstrate how to use `UpDraft` and functionality.

**Comment by jameslamb** [comment]
I changed the title of this. At a minimum, this project should have a vignette called `updraft-into.Rmd` that showcases the main functionality and explains why someone would use the project.

See @jayqi and @bburns632 's excellent work in [pkgnet](https://github.com/UptakeOpenSource/pkgnet/blob/master/vignettes/pkgnet-intro.Rmd) for example.

**Comment by mjermann** [comment]
vignette has been added, so closing this out!
