### ISSUE TITLE
should have a .gitignore

### ISSUE THREAD

**Issue by jameslamb** [UptakeOpenSource/updraft#4]
because of reasons

**Comment by zaynaib** [comment]
@jameslamb  can I take this issue on?

**Comment by jameslamb** [comment]
@zaynaib yes absolutely! Please let me know if you have any questions while working on it.

Thanks for contributing!

**Comment by zaynaib** [comment]
@jameslamb  I created the gitignore file. Let me know if there is anything else I can do for this project. If I made any mistakes let me know. Thanks for the opportunity to contribute :)
https://github.com/UptakeOpenSource/updraft/pull/22

**Comment by jameslamb** [comment]
@zaynaib thank you! I left a comment on there requesting that you add a few starting fields.

**Comment by zaynaib** [comment]
@jameslamb I made the following changes.
