### ISSUE TITLE
The Authors field in the DESCRIPTION file has a bug

### ISSUE THREAD

**Issue by mfrasco** [UptakeOpenSource/updraft#5]
There needs to be a parenthesis that closes this line: https://github.com/UptakeOpenSource/updraft/blob/master/DESCRIPTION#L5

And I think that this line https://github.com/UptakeOpenSource/updraft/blob/master/DESCRIPTION#L7 is redundant given the previous line.

**Comment by mfrasco** [comment]
This issue prevents the package from installing.

**Comment by jameslamb** [comment]
thanks for resolving this in #6 !
