### ISSUE TITLE
return(NULL) calls should be changed to return(invisible(NULL))

### ISSUE THREAD

**Issue by jameslamb** [UptakeOpenSource/updraft#7]
Very minor thing, but having `return(NULL)` can cause some weird things to happen in logs in certain situations.

Seeing this is always a bit confusing:

```
[INFO] doing some stuff...
[INFO] done
[INFO] doing other stuff....
NULL
[INFO] done
[INFO] moving on from stuff to things...
```

Using `return(invisible(NULL))` everywhere would suppress these NULLs from being printed

**Comment by cwschultz88** [comment]
Issue is address with last PR, closing this out!
